name: Build NtlmThief (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Restore NuGet packages
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Restore solution
        run: nuget restore NtlmThief.sln

      - uses: microsoft/setup-msbuild@v1
        name: Setup MSBuild

      - name: Build solution
        run: msbuild NtlmThief.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NtlmThief-Release-x32
          path: x32/Release/NtlmThief.exe
